apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: stress
  name: stress
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 480
  template:
    metadata:
      labels:
        app: stress
    spec:
      restartPolicy: Never
      securityContext:
          runAsUser: 1000
          runAsGroup: 3000
          fsGroup: 2000
      containers:
      #- image: alexeiled/stress-ng
      - image: ondsaft/wrlx-stress-ng:20.33.0
        name: stress
        command:
          - stress-ng
          - "--class"
          - "interrupt,memory,os,pipe,scheduler,cpu,cpu-cache,device,io,filesystem,vm"
          - "--all"
          - "1"
        resources:
          requests:
              memory: "6400Mi"
              cpu: "2500m"
          limits:
              memory: "12800Mi"
              cpu: "8000m"
        imagePullPolicy: Always
status: {}

