apiVersion: v1
kind: Service
metadata:
  name: nodeinfo
  labels:
    app: nodeinfo
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31115
  selector:
    app: nodeinfo
