apiVersion: v1
kind: Service
metadata:
  name: {{ include "theia.fullname" . }}
  labels:
{{ include "theia.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      nodePort: {{ .Values.service.nodeport}}
  selector:
    app.kubernetes.io/name: {{ include "theia.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
